# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '^.*\.snap$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-symlinks

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    - id: autopep8
      args: ["-i", "--max-line-length=150"]

-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
      name: flake8
      args: ["--max-line-length=150"]
